# Generated by Django 5.1.1 on 2024-09-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apirequestlog',
            name='forecast_date',
            field=models.DateTimeField(),
        ),
    ]
